QuestionList =[
"How many digits are there in Hindu-Arabic System?\n(1) 10\n(2) 20\n(3) 30\n(4) 40",
"Among the following which natural number has no predecessor?\n(1) 100\n(2) 200\n(3) 1\n(4) 0",
"Which among the following is the largest known number in the world?\n(1) ∞\n(2) googol\n(3) googolplex\n(4) gram",
"What does 1 googol means?\n(1) 1 followed by hundred zeros\n(2) 1 followed by thousand zeros\n(3) 1 followed by ten thousand zeros\n(4) 1 followed by 1 lakh zeros",
"Among the following which whole number has no predecessor?\n(1) –1\n(2) 0\n(3) 1\n(4) e		",
"Counting numbers are kept under ________ number.\n(1) Natural\n(2) Whole\n(3) Rational\n(4) Odd",
"An integer that is divisible by 2 is called:\n(1) Even number\n(2) Natural number\n(3) Odd number\n(4) Whole number",
"In which number system, there is no symbol for zero?\n(1) Hindu Arabic system\n(2) Roman\n(3) Egyptian\n(4) Mesopotamia",
"In Roman numerals M represents 1000, what does M represent?\n(1) 10,000\n(2) 50,000\n(3) 10,00,000\n(4) 500",
"What does D represent in Roman numeral system?\n(1) 100\n(2) 500\n(3) 1,000\n(4) 50",
"If 5 = V, How does 5,000 written in roman numeral system?\n(1) V\n(2) MMMMM\n(3) MX\n(4) VM",
"The whole number is denoted by __________.\n(1) N\n(2) R\n(3) W\n(4) Q",
"Rational number is represented by __________.\n(1) N\n(2) Z\n(3) R\n(4) Q",
"Integers are represented by __________.\n(1) W\n(2) Z\n(3) N\n(4) Q",
"All counting numbers, together with their negatives and zeros constitute the set of __________.\n(1) Whole number\n(2) Real number\n(3) Integers\n(4) Odd number",
"A number which is expressed as a + ib, where a and b are real are called:\n(1) Rational number\n(2) Irrational number\n(3) Complex number\n(4) Real number",
"A number which is expressed as a + ib, where a and b are real are called:\n(1) Rational number\n(2) Irrational number\n(3) Complex number\n(4) Real number",
"p, p + 2, p + 4 are called __________ if all numbers are primes.\n(1) Pythagorean Triplet\n(2) Prime Triplet\n(3) Lucas number\n(4) Fermat number",
"The cube root of 27 connected with units of angle measurement will produce __________ musical act?\n(1) The Three Degrees\n(2) The Square\n(3) The Rule of Three\n(4) Quadrilateral",
"A number only divisible by itself and one has inspired Joe Mac Anthony to title one of his works. What was the title of his work?\n(1) Prime Target\n(2) The Perfect Ten\n(3) The Amicable\n(4) The Pythagoras",
"Which of these could be either a circumference divided by π or a song written and recorded by David Bouie?\n(1) The Tangents\n(2) John of Arc\n(3) In search of last chord\n(4) The width of a circle",
"This number’s irrationality property was first discovered by Pythagoras. What is its value?\n(1) 2\n(2) 3\n(3) 5\n(4) 7",
"Any number in the form of 2p – 1, where p is a prime is known as:\n(1) Dual Prime\n(2) Goldbach Prime\n(3) Mersenne Prime\n(4) Golden Number",
"The sum of squares of first 7 prime number also satisfy the Lagrange’s Four Square theorem which states that “Every positive integer can be expressed as the sum of four squares”. What is the number I am talking about?\n(1) 666\n(2) 484\n(3) 1089\n(4) 6178",
"There are only 2 numbers that are twice the sum of their individual digits; one of them is zero (0). What is the other one?\n(1) 18\n(2) 27\n(3) 45\n(4) 40",
"What is the number called located on the bottom part of a fraction?\n(1) Numerator\n(2) Denominator\n(3) Componendo\n(4) Ratio",
"What is XLII in Arabic Numerals?\n(1) 42\n(2) 52\n(3) 62\n(4) 12",
"What do you get if you divide the number of hours in a week by the sum of the sides of a triangle, and the number of natural satellites of the earth?\n(1) 14\n(2) 28\n(3) 42\n(4) 56",
"Which number has just 3 prime factors of 2, 3 and 7?\n(1) 18\n(2) 24\n(3) 52\n(4) 42",
"Mutiply XXI by II and what result will you get in Roman number system?\n(1) XLII\n(2) XXIII\n(3) XXXXII\n(4) LXII",
"Which of the following number is an odd integer contains the digit 5, is divisible by 3 and lies between the square of 12 and 13?\n(1) 165\n(2) 175\n(3) 147\n(4) 185",
"The value of e = 2.71828… is also known as:\n(1) Archimedes Number\n(2) Fermat Number\n(3) Euler’s Number\n(4) Avagadro Number",
"The golden ratio is equivalent to 1.618… is denoted by a symbol Φ. What is the origin of this symbol?\n(1) Greek\n(2) Egypt\n(3) India\n(4) Arab",
"The golden ratio has been used by many architect in their structural plans for some famous buildings. Which of the following European building has the Golden ratio with its dimension?\n(1) Parthenon\n(2) Eiffel Tower\n(3) Taj Mahal\n(4) Qutub Minar",
"Which of the following is not a Pythagorean triplet?\n(1) (3, 4, 5)\n(2) (7, 24, 25)\n(3) (11, 60, 61)\n(4) (9, 41, 42)",
"What number, a one followed by 100 zeros, was first used by 9 year old Mitton Sirotta in 1940?\n(1) Googel\n(2) Googol\n(3) Golden\n(4) Round",
"What group of numbers does the letter ‘i’ represent?\n(1) Imaginary\n(2) Real\n(3) Perfect\n(4) Square",
"A number is called ______ if its number of factors and the sum of those factors are equal to perfect numbers.\n(1) Amicable number\n(2) Scalar\n(3) Sublime Number\n(4) Rational",
"A method of checking arithmetical calculation such as (+, –, ×, ÷) etc. is popularly known as :\n(1) Casting out Nines\n(2) ARLC Test\n(3) QED\n(4) Hopital Rule",
"Identify the number that cannot be used as a divisior:\n(1) ∞\n(2) – 5\n(3) 0\n(4) 4",
"Any two consecutive primes which differ by 2 are known as\n(1) Twin Primes\n(2) Mersenne Prime\n(3) Goldbach Cayocture\n(4) Co-prime",
"Numbers having positive or negative sign is called __________.\n(1) Positive number\n(2) Directed number\n(3) Scalar\n(4) Prime",
"Besides 1, which of the following number is both squares and triangular number?\n(1) 25\n(2) 10\n(3) 36\n(4) 80",
"Which of the following is transcendental number?\n(1) e and π\n(2) i and e\n(3) Φ and Ψ\n(4) α and β",
"The famous Bakhshali manuscript was written in ________ script.\n(1) Devnagri\n(2) Sanskrit\n(3) Sarada\n(4) Brabmi",
"What is the value of Golden ratio which is made popular recently by the book the Da Vinci Code?\n(1) 1.414\n(2) 1.618\n(3) 1.723\n(4) 3.142",
"Palindromic numbers are numbers that read the same backwards as forwards. The world Palindrome comes from the Greek word Palindromes. What is its meaning?\n(1) Moving\n(2) Kicking\n(3) Running back again\n(4) Laughing",
"Which numbers appear in Don Brown’s best selling novel ‘The Da Vinci Code’?\n(1) Fermat number\n(2) Fibonacci number\n(3) Lucas number\n(4) Golden number",
"A system of notation that uses the base 3 instead of base 10 is called:\n(1) Binary system\n(2) Ternery system\n(3) Hex system\n(4) Octagonal system",
"A system of notation that uses the base 2 instead of base 10 is called:\n(1) Binary system\n(2) Ternary system\n(3) Hex system\n(4) Hexagonal system"
]



AnswerList=["1", "3", "3", "1", "2", "1", "1", "2", "3", "2", "1", "3", "3", "2", "3", "3", "3", "2", "1", "1", "4", "1", "3", "1", "1", "2", "1", "3", "4", "1", "1", "3", "1", "1", "4", "2", "1", "3", "1", "3", "1", "2", "3", "1", "3", "2", "3", "2", "2", "2"]


